name: "Generate AI Documentation"
description: "Generate professional code documentation using OpenAI"
inputs:
  openai_api_key:
    description: "Your OpenAI API key"
    required: true
  path:
    description: "Path to the code folder to document"
    required: true
    default: "."
runs:
  using: "node24"
  main: "dist/index.js"
branding:
  color: "blue"
  icon: "book"
